Repository hassio-addons/addon-ubuntu-base, pull requests merged in 2025-01, with the labels that each got.

#158 :fireworks: Updates maintenance/license year to 2025
  LICENSE.md
  README.md
Labels: maintenance

#160 Update curl to 8.5.0-2ubuntu10.6
  base/Dockerfile
Labels: dependencies

#161 Update README
  README.md
Labels: documentation
